/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import assignment.classes.*;
import java.awt.print.PrinterException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setLocationRelativeTo(null);// Display at the centre of the screen
        
        //Display the data from textfiles in tables
        displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\RoomID.txt",tableViewRoom);
        displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\RoomID.txt",tableViewRoom2);
        displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", tableManageBooking);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpNationality = new javax.swing.ButtonGroup();
        grpNationality2 = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        btnHome2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnNewBooking = new javax.swing.JButton();
        btnManageBooking = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JTabbedPane = new javax.swing.JTabbedPane();
        HomePage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNewBooking2 = new javax.swing.JButton();
        btnManageBooking1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        NewBooking = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        dateCODate = new com.toedter.calendar.JDateChooser();
        dateCIDate = new com.toedter.calendar.JDateChooser();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableViewRoom = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        ManageBooking = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableManageBooking = new javax.swing.JTable();
        txtKeyword = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        NewBooking2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dateCODate2 = new com.toedter.calendar.JDateChooser();
        dateCIDate2 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        txtStayoverNights = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtContactNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtICPassport = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        radForeigner = new javax.swing.JRadioButton();
        radMalaysian = new javax.swing.JRadioButton();
        btnSubmit2 = new javax.swing.JButton();
        btnReset2 = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        lblRoomID = new javax.swing.JLabel();
        ManageInfo = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        receipt = new javax.swing.JTextArea();
        btnGenerateReceipt = new javax.swing.JButton();
        btnPrintReceipt = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lblBookingID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblContactNumber = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblICPassport = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        lblCID = new javax.swing.JLabel();
        lblCOD = new javax.swing.JLabel();
        lblRID = new javax.swing.JLabel();
        btnDeleteData = new javax.swing.JButton();
        btnEditCustomer = new javax.swing.JButton();
        btnEditBookingDetail = new javax.swing.JButton();
        EditBooking = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        dateCODate3 = new com.toedter.calendar.JDateChooser();
        dateCIDate3 = new com.toedter.calendar.JDateChooser();
        btnSearch3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableViewRoom2 = new javax.swing.JTable();
        btnSubmit3 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        lblBookingID2 = new javax.swing.JLabel();
        btnReturn2 = new javax.swing.JButton();
        EditCustomer = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtName2 = new javax.swing.JTextField();
        txtContactNumber2 = new javax.swing.JTextField();
        txtEmail2 = new javax.swing.JTextField();
        txtICPassport2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        radForeigner2 = new javax.swing.JRadioButton();
        radMalaysian2 = new javax.swing.JRadioButton();
        btnSubmit4 = new javax.swing.JButton();
        btnReturn3 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        lblBookingID3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Deuce Hotel");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(153, 153, 153));
        Header.setMinimumSize(new java.awt.Dimension(926, 100));

        btnHome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/logo_small.png"))); // NOI18N
        btnHome2.setActionCommand("Home");
        btnHome2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome2.setPreferredSize(new java.awt.Dimension(60, 60));
        btnHome2.setRolloverEnabled(false);
        btnHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome2ActionPerformed(evt);
            }
        });
        Header.add(btnHome2);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Header.add(jPanel2);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnDefault.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setPreferredSize(new java.awt.Dimension(150, 60));
        btnHome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnHover.png"))); // NOI18N
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnSelect.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        Header.add(btnHome);

        btnNewBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnDefault.png"))); // NOI18N
        btnNewBooking.setText("New Booking");
        btnNewBooking.setActionCommand("Home");
        btnNewBooking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewBooking.setPreferredSize(new java.awt.Dimension(150, 60));
        btnNewBooking.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnHover.png"))); // NOI18N
        btnNewBooking.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnSelect.png"))); // NOI18N
        btnNewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBookingActionPerformed(evt);
            }
        });
        Header.add(btnNewBooking);

        btnManageBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnDefault.png"))); // NOI18N
        btnManageBooking.setText("Manage Booking");
        btnManageBooking.setActionCommand("Home");
        btnManageBooking.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManageBooking.setPreferredSize(new java.awt.Dimension(150, 60));
        btnManageBooking.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnHover.png"))); // NOI18N
        btnManageBooking.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/btnSelect.png"))); // NOI18N
        btnManageBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBookingActionPerformed(evt);
            }
        });
        Header.add(btnManageBooking);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 60));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Header.add(jPanel3);

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        JTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("The Deuce Hotel");

        btnNewBooking2.setText("New Booking");
        btnNewBooking2.setActionCommand("Home");
        btnNewBooking2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewBooking2.setPreferredSize(new java.awt.Dimension(150, 60));
        btnNewBooking2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBooking2ActionPerformed(evt);
            }
        });

        btnManageBooking1.setText("Manage Booking");
        btnManageBooking1.setActionCommand("Home");
        btnManageBooking1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnManageBooking1.setPreferredSize(new java.awt.Dimension(150, 60));
        btnManageBooking1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBooking1ActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.setActionCommand("Home");
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.setPreferredSize(new java.awt.Dimension(150, 60));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Object[][] data = ReadFile.readFile("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt");
        jLabel3.setText("Total Customers: "+ data.length);

        javax.swing.GroupLayout HomePageLayout = new javax.swing.GroupLayout(HomePage);
        HomePage.setLayout(HomePageLayout);
        HomePageLayout.setHorizontalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnNewBooking2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(btnManageBooking1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePageLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(323, 323, 323))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePageLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(376, 376, 376))))
        );
        HomePageLayout.setVerticalGroup(
            HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePageLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(HomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewBooking2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageBooking1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(jLabel3)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Home", HomePage);

        jPanel13.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Check-In Date : ");

        jLabel25.setText("Check-Out Date :");

        dateCODate.setMinSelectableDate(new Date());

        dateCIDate.setMinSelectableDate(new Date());

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/search_icon.png"))); // NOI18N
        btnSearch.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tableViewRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableViewRoom.setRowHeight(25);
        jScrollPane1.setViewportView(tableViewRoom);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnSubmit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateCIDate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(dateCODate, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCODate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCIDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout NewBookingLayout = new javax.swing.GroupLayout(NewBooking);
        NewBooking.setLayout(NewBookingLayout);
        NewBookingLayout.setHorizontalGroup(
            NewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewBookingLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        NewBookingLayout.setVerticalGroup(
            NewBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewBookingLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("New Booking", NewBooking);

        ManageBooking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableManageBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableManageBooking.setRowHeight(25);
        jScrollPane2.setViewportView(tableManageBooking);

        ManageBooking.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 880, -1));

        txtKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeywordActionPerformed(evt);
            }
        });
        ManageBooking.add(txtKeyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 120, 30));

        btnSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/search_icon.png"))); // NOI18N
        btnSearch2.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });
        ManageBooking.add(btnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        btnManage.setText("Manage");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        ManageBooking.add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, -1, 30));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/refresh_icon.png"))); // NOI18N
        btnRefresh.setPreferredSize(new java.awt.Dimension(30, 30));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        ManageBooking.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));

        JTabbedPane.addTab("Manage Booking", ManageBooking);

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setText("Check-in Date : ");

        jLabel9.setText("Check-out Date : ");

        jLabel10.setText("Room ID :");

        jLabel11.setText("Email : ");

        jLabel12.setText("Contact Number : ");

        jLabel13.setText("Name : ");

        jLabel14.setText("IC / Passport :  ");

        dateCODate2.setEnabled(false);
        dateCODate2.setMinSelectableDate(new Date());

        dateCIDate2.setEnabled(false);
        dateCIDate2.setMinSelectableDate(new Date());

        jLabel15.setText("Stayover Night(s) :");

        txtStayoverNights.setEnabled(false);
        txtStayoverNights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStayoverNightsActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumberActionPerformed(evt);
            }
        });

        jLabel16.setText("Nationality : ");

        grpNationality.add(radForeigner);
        radForeigner.setText("Foreigner");

        grpNationality.add(radMalaysian);
        radMalaysian.setText("Malaysian");

        btnSubmit2.setText("Submit");
        btnSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit2ActionPerformed(evt);
            }
        });

        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        btnReturn.setText("Return");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReturn)
                .addGap(18, 18, 18)
                .addComponent(btnReset2)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit2)
                .addGap(52, 52, 52))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dateCIDate2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(dateCODate2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblRoomID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtContactNumber)
                                        .addComponent(jLabel14)
                                        .addComponent(txtICPassport)
                                        .addComponent(radForeigner, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addComponent(txtStayoverNights, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(radMalaysian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateCIDate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateCODate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStayoverNights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRoomID))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICPassport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radMalaysian)
                    .addComponent(radForeigner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit2)
                    .addComponent(btnReset2)
                    .addComponent(btnReturn))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout NewBooking2Layout = new javax.swing.GroupLayout(NewBooking2);
        NewBooking2.setLayout(NewBooking2Layout);
        NewBooking2Layout.setHorizontalGroup(
            NewBooking2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewBooking2Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        NewBooking2Layout.setVerticalGroup(
            NewBooking2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewBooking2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("New Booking(2)", NewBooking2);

        jPanel12.setBackground(new java.awt.Color(204, 204, 204));
        jPanel12.setMinimumSize(new java.awt.Dimension(222, 122));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Check-In Date");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel7.setText("Check-Out Date");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabel8.setText("Room ID ");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabel17.setText("Name  ");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel18.setText("Email ");
        jPanel12.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel19.setText("Contact Number  ");
        jPanel12.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel20.setText("IC / Passport ");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Booking Detail ");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Customer's Information ");
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        receipt.setEditable(false);
        receipt.setColumns(20);
        receipt.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        receipt.setRows(5);
        jScrollPane3.setViewportView(receipt);

        jPanel12.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 342, 394));

        btnGenerateReceipt.setText("Generate Receipt");
        btnGenerateReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReceiptActionPerformed(evt);
            }
        });
        jPanel12.add(btnGenerateReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 130, 55));

        btnPrintReceipt.setText("Print Receipt");
        btnPrintReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintReceiptActionPerformed(evt);
            }
        });
        jPanel12.add(btnPrintReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 130, 55));

        jLabel23.setText("Nationality ");
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel24.setText("Booking ID");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblBookingID.setText("bid");
        jPanel12.add(lblBookingID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        lblName.setText("name");
        jPanel12.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        lblContactNumber.setText("number");
        jPanel12.add(lblContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        lblEmail.setText("email");
        jPanel12.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        lblICPassport.setText("icp");
        jPanel12.add(lblICPassport, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        lblNationality.setText("nat");
        jPanel12.add(lblNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        lblCID.setText("cid");
        jPanel12.add(lblCID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        lblCOD.setText("cod");
        jPanel12.add(lblCOD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        lblRID.setText("rid");
        jPanel12.add(lblRID, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        btnDeleteData.setText("Delete Data");
        btnDeleteData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDataActionPerformed(evt);
            }
        });
        jPanel12.add(btnDeleteData, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 130, 55));

        btnEditCustomer.setText("Edit Customer Info");
        btnEditCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditCustomerActionPerformed(evt);
            }
        });
        jPanel12.add(btnEditCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, -1));

        btnEditBookingDetail.setText("Edit Booking Detail");
        btnEditBookingDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookingDetailActionPerformed(evt);
            }
        });
        jPanel12.add(btnEditBookingDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, -1));

        javax.swing.GroupLayout ManageInfoLayout = new javax.swing.GroupLayout(ManageInfo);
        ManageInfo.setLayout(ManageInfoLayout);
        ManageInfoLayout.setHorizontalGroup(
            ManageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageInfoLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        ManageInfoLayout.setVerticalGroup(
            ManageInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageInfoLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Manage", ManageInfo);

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));

        jLabel26.setText("Check-In Date : ");

        jLabel27.setText("Check-Out Date :");

        dateCODate3.setMinSelectableDate(new Date());

        dateCIDate3.setMinSelectableDate(new Date());

        btnSearch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/image/search_icon.png"))); // NOI18N
        btnSearch3.setPreferredSize(new java.awt.Dimension(30, 30));
        btnSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch3ActionPerformed(evt);
            }
        });

        tableViewRoom2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableViewRoom2.setRowHeight(25);
        jScrollPane4.setViewportView(tableViewRoom2);

        btnSubmit3.setText("Submit");
        btnSubmit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit3ActionPerformed(evt);
            }
        });

        jLabel37.setText("Booking ID : ");

        lblBookingID2.setText("bid");

        btnReturn2.setText("Return");
        btnReturn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBookingID2))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel14Layout.createSequentialGroup()
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateCIDate3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(dateCODate3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnReturn2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit3)
                        .addGap(80, 80, 80))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(lblBookingID2))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCODate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateCIDate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit3)
                    .addComponent(btnReturn2))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout EditBookingLayout = new javax.swing.GroupLayout(EditBooking);
        EditBooking.setLayout(EditBookingLayout);
        EditBookingLayout.setHorizontalGroup(
            EditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBookingLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        EditBookingLayout.setVerticalGroup(
            EditBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditBookingLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Edit Booking", EditBooking);

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));

        jLabel31.setText("Email : ");

        jLabel32.setText("Contact Number : ");

        jLabel33.setText("Name : ");

        jLabel34.setText("IC / Passport :  ");

        txtName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName2ActionPerformed(evt);
            }
        });

        txtContactNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumber2ActionPerformed(evt);
            }
        });

        jLabel36.setText("Nationality : ");

        grpNationality2.add(radForeigner2);
        radForeigner2.setText("Foreigner");

        grpNationality2.add(radMalaysian2);
        radMalaysian2.setText("Malaysian");

        btnSubmit4.setText("Submit");
        btnSubmit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmit4ActionPerformed(evt);
            }
        });

        btnReturn3.setText("Return");
        btnReturn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturn3ActionPerformed(evt);
            }
        });

        jLabel38.setText("Booking ID : ");

        lblBookingID3.setText("bid");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContactNumber2)
                            .addComponent(jLabel34)
                            .addComponent(txtICPassport2)
                            .addComponent(radForeigner2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(98, 98, 98))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBookingID3))
                            .addComponent(jLabel36)
                            .addComponent(radMalaysian2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnReturn3)
                .addGap(81, 81, 81)
                .addComponent(btnSubmit4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(lblBookingID3))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContactNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtICPassport2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radMalaysian2)
                    .addComponent(radForeigner2))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit4)
                    .addComponent(btnReturn3))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EditCustomerLayout = new javax.swing.GroupLayout(EditCustomer);
        EditCustomer.setLayout(EditCustomerLayout);
        EditCustomerLayout.setHorizontalGroup(
            EditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditCustomerLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        EditCustomerLayout.setVerticalGroup(
            EditCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditCustomerLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Edit Customer", EditCustomer);

        getContentPane().add(JTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 36, 940, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        //updates the number of customers
        data = ReadFile.readFile("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt");
        jLabel3.setText("Total Customers: "+ data.length);
        //Leads to Home
        JTabbedPane.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnManageBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBookingActionPerformed
        //Acts as a reset button to retrieve updated data from textfile
        model = (DefaultTableModel) tableManageBooking.getModel();
        model.setRowCount(0);
        displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", tableManageBooking);
        //Leads to Manage Booking
        JTabbedPane.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageBookingActionPerformed

    private void btnNewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBookingActionPerformed
        //Resets all the textfield
        if (CIDate != null || CODate != null){
            CIDate.setTime(0);
            CODate.setTime(0);
        }
        dateCIDate.setDate(null);
        dateCODate.setDate(null);
        txtName.setText("");
        txtContactNumber.setText("");
        txtEmail.setText("");
        txtICPassport.setText("");
        radMalaysian.setSelected(false);
        radForeigner.setSelected(false);
        receipt.setText("");
        //Leads to New Booking
        JTabbedPane.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewBookingActionPerformed

    private void btnHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome2ActionPerformed
        //Also leads to Home
        JTabbedPane.setSelectedIndex(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHome2ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        //Reset value
        dateCIDate.setDate(null);
        dateCODate.setDate(null);
        CIDate.setTime(0);
        CODate.setTime(0);
        //Back to find date and room
        JTabbedPane.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumberActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        //Reset value
        txtName.setText("");
        txtContactNumber.setText("");
        txtEmail.setText("");
        txtICPassport.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit2ActionPerformed
        
        //Creates a empty error then adds the error when occur
        Message = "";
        if (!validate.alphabetValidation(txtName.getText())) Message += "Please Input Alphabets Only in Name\n";
        if (!validate.numberValidation(txtContactNumber.getText())) Message += "Please Input Numbers Only in Contact Number\n";
        if (!validate.emailValidation(txtEmail.getText())) Message += "Please Input Correct Email in Email\n";
        if (!validate.passportValidation(txtICPassport.getText())) Message += "Please Input Alphanumeric Only in IC/Passport\n";
        if (!radForeigner.isSelected()&&!radMalaysian.isSelected()) Message += "Please Select Customer's Nationality\n";
        
        if (!Message.equals("")){
            JOptionPane.showMessageDialog(null, Message, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Read lines in textfile
        lines = 0;
        try (BufferedReader reader = new BufferedReader(new FileReader("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt"))) {
            while (reader.readLine() != null) lines++;
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error reading file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        if (lines == 1){
            bID = "BK0001";
        }
        else{
            //Algo to create bookingid when textfile not empty
            String latestKey = null;
            try{
                BufferedReader br = new BufferedReader(new FileReader("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt"));

                for (int i = 0; i < lines - 1; i++){
                    br.readLine();
                }
                String[] row = br.readLine().split(",");
                latestKey = row[0];
                
            }catch(IOException er) {
                JOptionPane.showMessageDialog(null, "Error reading file: " + er.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            Pattern pattern = Pattern.compile("\\d+");
            Matcher matcher = pattern.matcher(latestKey);
            if (matcher.find()) {
                int numericValue = Integer.parseInt(matcher.group());
                numericValue++;
                bID = "BK" + String.format("%04d", numericValue);
            }
        }
        
        
        cID = formatter.format(dateCIDate2.getDate());
        cOD = formatter.format(dateCODate2.getDate());
        rID = lblRoomID.getText();
        name = txtName.getText();
        c = txtContactNumber.getText();
        e = txtEmail.getText();
        iCP = txtICPassport.getText();

        if (radMalaysian.isSelected())
            nat = radMalaysian.getText();
        else if (radForeigner.isSelected())
            nat = radForeigner.getText();

        //save into textfile
        SaveData customer = new SaveData(bID, cID, cOD, rID, name, c, e, iCP, nat);
        String result = customer.saveData();
        if(result == "Success")
            JOptionPane.showMessageDialog(null,"Registration completed.","Success",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Could not write into file due to " + result,"Error",JOptionPane.ERROR_MESSAGE);
        
        lblName.setText(name);
        lblContactNumber.setText(c);
        lblEmail.setText(e);
        lblICPassport.setText(iCP);
        lblCID.setText(cID);
        lblCOD.setText(cOD);
        lblRID.setText(lblRoomID.getText());
        lblBookingID.setText(bID); 
        lblNationality.setText(nat);
        //leads to conclusion for booking
        JTabbedPane.setSelectedIndex(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit2ActionPerformed

    private void txtKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeywordActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        //get keyword field to search
        keyword = txtKeyword.getText();
        search.searchBookingInfo("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", keyword,tableManageBooking);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnGenerateReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReceiptActionPerformed
        //regenerate and replace if pressed 
        receipt.setText(generate.generateReceipt(lblCID.getText(),lblCOD.getText(),lblRID.getText(), lblName.getText(),lblContactNumber.getText(),lblEmail.getText(),lblICPassport.getText(),lblNationality.getText())); 
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateReceiptActionPerformed

    private void txtStayoverNightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStayoverNightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStayoverNightsActionPerformed

    private void btnPrintReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintReceiptActionPerformed
        if (!receipt.getText().equals("")){
            try {
                receipt.print();
            } catch (PrinterException ex) {
                //auto generated
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Receipt is Empty, Click on Generate Receipt to Generate Receipt" , "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintReceiptActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        //gets row of table selected
        rowSelected = tableManageBooking.getSelectedRow();
        
        if (rowSelected != -1) {
            //gets data of row of table
            int columnNumber = tableManageBooking.getModel().getColumnCount();
            String[] data = new String[columnNumber];
            for (int i = 0; i < columnNumber; i++) {
                data[i] = (String)tableManageBooking.getValueAt(rowSelected, i);
            }
            
            //fills in the data in the fields
            lblBookingID.setText(data[0]);
            lblCID.setText(data[1]);
            lblCOD.setText(data[2]);
            lblRID.setText(data[3]);
            lblName.setText(data[4]);
            lblContactNumber.setText(data[5]);
            lblEmail.setText(data[6]);
            lblICPassport.setText(data[7]);
            lblNationality.setText(data[8]);
            receipt.setText("");
            //lead to conclusion of booking
            JTabbedPane.setSelectedIndex(4);
        }else{
             JOptionPane.showMessageDialog(null, "No Row Selected" , "Error", JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageActionPerformed
    
    
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        
        LocalDateTime now = LocalDateTime.now();
        String dateTimeNow = now.format(dateNowFormatter);
        
        //If no dates selected
        if(dateCIDate.getDate()==null||dateCODate.getDate()==null){
            JOptionPane.showMessageDialog(null, "Error : Please Select Check-In Date and Check-Out Date Before Booking", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        CIDate = dateCIDate.getDate();
        CODate = dateCODate.getDate();
        
        //to make the diff between time2-time1 and time1-time2, opposite shows positive
        if (CIDate.getTime()>CODate.getTime()){
            typeOfInteger = "-";
        }else{
            typeOfInteger = "";
        }

        diffInMillies = Math.abs(CODate.getTime() - CIDate.getTime());
        diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
        stayoverNights = (Integer.parseInt(typeOfInteger + diff));
        
        try{
            //if booking date doesnt make sense
            if (stayoverNights < 1) throw new Exception ("Wrong Input of Date, Try Again");
            //convert to string and back to date so the hh/MM/yyyy gets reset,will show time now if doesnt do this
            CIDate = formatter.parse(formatter.format(dateCIDate.getDate()));
            CODate = formatter.parse(formatter.format(dateCODate.getDate()));
        }catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        check.checkAvailableRoom(tableViewRoom, CIDate, CODate);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        rowSelected = tableViewRoom.getSelectedRow();
        selectedRoom = null;
        
        //when the cicodates have not been set or 
        if (CIDate == null || CIDate.getTime() == 0||(CODate)== null|| CODate.getTime() == 0){

            JOptionPane.showMessageDialog(null, "Error : Please Press The Search Button To Search For Available Rooms", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        
        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(null, "Error : No Room Selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            selectedRoom = (String) tableViewRoom.getValueAt(rowSelected, 0);
        }
        
        
        dateCIDate2.setDate(CIDate);
        dateCODate2.setDate(CODate);
        lblRoomID.setText(selectedRoom);
        txtStayoverNights.setText(Integer.toString(stayoverNights));
        JTabbedPane.setSelectedIndex(3);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDeleteDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDataActionPerformed
        option = JOptionPane.showConfirmDialog(null,"Would you like to delete the data?","Delete Data ",JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION){
            change.deleteRowData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", lblBookingID.getText());
            //reset table
            model = (DefaultTableModel) tableManageBooking.getModel();
            model.setRowCount(0);
            displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", tableManageBooking);
            JOptionPane.showMessageDialog(null, "Data Deleted!", "Deleted", JOptionPane.INFORMATION_MESSAGE);
            //leads back to Manage
            JTabbedPane.setSelectedIndex(2);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteDataActionPerformed

    private void btnEditCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditCustomerActionPerformed

        lblBookingID3.setText(lblBookingID.getText());
        txtName2.setText(lblName.getText());
        txtContactNumber2.setText(lblContactNumber.getText());
        txtEmail2.setText(lblEmail.getText());
        txtICPassport2.setText(lblICPassport.getText());
        if (lblNationality.getText().equals("Malaysian")){
            radMalaysian2.setSelected(true);
        }else{
            radForeigner2.setSelected(true);
        }
        //leads to editcustomerdetail
        JTabbedPane.setSelectedIndex(6);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditCustomerActionPerformed

    private void btnEditBookingDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookingDetailActionPerformed
        
        try{
            //string to date to be shown in jdatechooser
            CIDate = formatter.parse(lblCID.getText());
            CODate = formatter.parse(lblCOD.getText());
        }catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        lblBookingID2.setText(lblBookingID.getText());
        dateCIDate3.setDate(CIDate);
        dateCODate3.setDate(CODate);
        
        check.checkAvailableRoom(tableViewRoom2, CIDate, CODate);
        //to editbookingdetail
        JTabbedPane.setSelectedIndex(5);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditBookingDetailActionPerformed

    private void btnSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch3ActionPerformed
        CIDate = dateCIDate3.getDate();
        CODate = dateCODate3.getDate();

        if (CIDate.getTime()>CODate.getTime()){
            typeOfInteger = "-";
        }else{
            typeOfInteger = "";
        }

        diffInMillies = Math.abs(CODate.getTime() - CIDate.getTime());
        diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
        stayoverNights = (Integer.parseInt(typeOfInteger + diff));
        try{
            if (stayoverNights < 1) throw new Exception ("Wrong Input of Date, Try Again");
            //convert to string and back to date so the hh/MM/yyyy gets reset,will show time now if doesnt do this
            CIDate = formatter.parse(formatter.format(dateCIDate3.getDate()));
            CODate = formatter.parse(formatter.format(dateCODate3.getDate()));
        }catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error : " + e.getMessage() , "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        check.checkAvailableRoom(tableViewRoom2, CIDate, CODate);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearch3ActionPerformed

    private void btnSubmit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit3ActionPerformed
        rowSelected = tableViewRoom2.getSelectedRow();
        selectedRoom = null;
        editedData = new String[4];
        //to ensure borh dates are selected
        if (CIDate == null || CIDate.getTime() == 0||(CODate)== null|| CODate.getTime() == 0){

            JOptionPane.showMessageDialog(null, "Error : Please Press The Search Button To Search For Available Rooms", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (rowSelected == -1) {
            JOptionPane.showMessageDialog(null, "Error : No Room Selected", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            selectedRoom = (String) tableViewRoom2.getValueAt(rowSelected, 0);
        }
        
        
        editedData[0] = lblBookingID2.getText();
        editedData[1] = formatter.format(dateCIDate3.getDate());
        editedData[2] = formatter.format(dateCODate3.getDate());
        editedData[3] = selectedRoom;
        
        change.editRowData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", editedData);
        JOptionPane.showMessageDialog(null, "Data Updated!", "Updated", JOptionPane.INFORMATION_MESSAGE);
        //replace data shown to new data
        lblCID.setText(editedData[1]);
        lblCOD.setText(editedData[2]);
        lblRID.setText(editedData[3]);
        //back to manage
        JTabbedPane.setSelectedIndex(4);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit3ActionPerformed

    private void txtName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName2ActionPerformed

    private void txtContactNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumber2ActionPerformed

    private void btnSubmit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmit4ActionPerformed

        //Creates a empty error then adds the error when occur
        Message = "";
        if (!validate.alphabetValidation(txtName2.getText())) Message += "Please Input Alphabets Only in Name\n";
        if (!validate.numberValidation(txtContactNumber2.getText())) Message += "Please Input Numbers Only in Contact Number\n";
        if (!validate.emailValidation(txtEmail2.getText())) Message += "Please Input Correct Email in Email\n";
        if (!validate.passportValidation(txtICPassport2.getText())) Message += "Please Input Alphanumeric Only in IC/Passport\n";
        if (!radForeigner2.isSelected()&&!radMalaysian2.isSelected()) Message += "Please Select Customer's Nationality\n";
        
        if (!Message.equals("")){
            JOptionPane.showMessageDialog(null, Message, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        editedData = new String[6];
        
        if (radMalaysian2.isSelected()){
            nat = "Malaysian";
        }else{
            nat = "Foreigner";
        }
        
        editedData[0] = lblBookingID3.getText();
        editedData[1] = txtName2.getText();
        editedData[2] = txtContactNumber2.getText();
        editedData[3] = txtEmail2.getText();
        editedData[4] = txtICPassport2.getText();
        editedData[5] = nat;
        
        change.editRowData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", editedData);
        JOptionPane.showMessageDialog(null, "Data Updated!", "Updated", JOptionPane.INFORMATION_MESSAGE);
        
        //replace shown
        lblName.setText(editedData[1]);
        lblContactNumber.setText(editedData[2]);
        lblEmail.setText(editedData[3]);
        lblICPassport.setText(editedData[4]);
        lblNationality.setText(editedData[5]);
        ////back to conclusion of booking
        JTabbedPane.setSelectedIndex(4);
                
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmit4ActionPerformed

    private void btnReturn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn3ActionPerformed
        //back to conclusion of booking
        JTabbedPane.setSelectedIndex(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturn3ActionPerformed

    private void btnReturn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturn2ActionPerformed
        //back to conclusion of booking 
        JTabbedPane.setSelectedIndex(4);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReturn2ActionPerformed

    private void btnNewBooking2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBooking2ActionPerformed
        //reset
        if (CIDate != null || CODate != null){
            CIDate.setTime(0);
            CODate.setTime(0);
        }
        dateCIDate.setDate(null);
        dateCODate.setDate(null);
        txtName.setText("");
        txtContactNumber.setText("");
        txtEmail.setText("");
        txtICPassport.setText("");
        radMalaysian.setSelected(false);
        radForeigner.setSelected(false);
        receipt.setText("");
        //lead to new booking
        JTabbedPane.setSelectedIndex(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewBooking2ActionPerformed

    private void btnManageBooking1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBooking1ActionPerformed
        //reset, show newest
        model = (DefaultTableModel) tableManageBooking.getModel();
        model.setRowCount(0);
        displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", tableManageBooking);
        JTabbedPane.setSelectedIndex(2);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageBooking1ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        option = JOptionPane.showConfirmDialog(null,"Would you like to logout?","Logout",JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION){
            //hide mainpage and back to login
            Login login = new Login();
            login.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        //button incase refresh doesnt work
        txtKeyword.setText("");
        model = (DefaultTableModel) tableManageBooking.getModel();
        model.setRowCount(0);
        displayData.displayTableData("C:\\Users\\Acer\\OneDrive\\Documents\\NetBeansProjects\\Assignment\\src\\assignment\\data\\Booking.txt", tableManageBooking);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    private String bID = null, cID, cOD, rID, name, c, e, iCP, nat = null,typeOfInteger = "",selectedRoom = null,Message,keyword;
    private int stayoverNights ,rowSelected, option;
    private Date CIDate, CODate;
    long diffInMillies, diff, lines;
    private String[] editedData;
    private Object[][] data;
    private DefaultTableModel model;
    private DisplayTableData displayData = new DisplayTableData();
    private CheckAvailbleRoom check = new CheckAvailbleRoom();
    private ChangeRowData change = new ChangeRowData();
    private Validation validate =  new Validation();
    private GenerateReceipt generate = new GenerateReceipt();
    private SearchBookingInfo search = new SearchBookingInfo();
    private SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    private DateTimeFormatter dateNowFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditBooking;
    private javax.swing.JPanel EditCustomer;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel HomePage;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JPanel ManageBooking;
    private javax.swing.JPanel ManageInfo;
    private javax.swing.JPanel NewBooking;
    private javax.swing.JPanel NewBooking2;
    private javax.swing.JButton btnDeleteData;
    private javax.swing.JButton btnEditBookingDetail;
    private javax.swing.JButton btnEditCustomer;
    private javax.swing.JButton btnGenerateReceipt;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHome2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnManageBooking;
    private javax.swing.JButton btnManageBooking1;
    private javax.swing.JButton btnNewBooking;
    private javax.swing.JButton btnNewBooking2;
    private javax.swing.JButton btnPrintReceipt;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturn2;
    private javax.swing.JButton btnReturn3;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnSearch3;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmit2;
    private javax.swing.JButton btnSubmit3;
    private javax.swing.JButton btnSubmit4;
    private com.toedter.calendar.JDateChooser dateCIDate;
    private com.toedter.calendar.JDateChooser dateCIDate2;
    private com.toedter.calendar.JDateChooser dateCIDate3;
    private com.toedter.calendar.JDateChooser dateCODate;
    private com.toedter.calendar.JDateChooser dateCODate2;
    private com.toedter.calendar.JDateChooser dateCODate3;
    private javax.swing.ButtonGroup grpNationality;
    private javax.swing.ButtonGroup grpNationality2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBookingID;
    private javax.swing.JLabel lblBookingID2;
    private javax.swing.JLabel lblBookingID3;
    private javax.swing.JLabel lblCID;
    private javax.swing.JLabel lblCOD;
    private javax.swing.JLabel lblContactNumber;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblICPassport;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblRID;
    private javax.swing.JLabel lblRoomID;
    private javax.swing.JRadioButton radForeigner;
    private javax.swing.JRadioButton radForeigner2;
    private javax.swing.JRadioButton radMalaysian;
    private javax.swing.JRadioButton radMalaysian2;
    private javax.swing.JTextArea receipt;
    private javax.swing.JTable tableManageBooking;
    private javax.swing.JTable tableViewRoom;
    private javax.swing.JTable tableViewRoom2;
    private javax.swing.JTextField txtContactNumber;
    private javax.swing.JTextField txtContactNumber2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail2;
    private javax.swing.JTextField txtICPassport;
    private javax.swing.JTextField txtICPassport2;
    private javax.swing.JTextField txtKeyword;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtStayoverNights;
    // End of variables declaration//GEN-END:variables
}
